import type { GridThemeInput, ThemePreset } from '../types';

/**
 * Built-in theme presets. Each one is a partial theme layered on the default,
 * so a preset only states what makes it distinctive.
 */
export const themePresets: Record<Exclude<ThemePreset, 'system'>, GridThemeInput> = {
  default: {
    name: 'default',
  },

  modern: {
    name: 'modern',
    colors: {
      primary: '#4F46E5',
      primaryHover: '#4338CA',
      headerBackground: '#FFFFFF',
      headerText: '#0F172A',
      border: '#EEF2F7',
      rowHover: '#EEF2FF',
      rowSelected: '#E0E7FF',
      rowSelectedHover: '#C7D2FE',
      hoverOverlay: 'rgba(79, 70, 229, 0.08)',
      activeOverlay: 'rgba(79, 70, 229, 0.16)',
    },
    radius: { container: '14px', md: '8px', lg: '12px' },
    shadows: { container: '0 1px 2px rgba(16,24,40,.05), 0 8px 24px -12px rgba(16,24,40,.12)' },
    typography: { headerFontSize: '12px', headerFontWeight: 600, letterSpacing: '0.02em' },
    header: { height: 46, textTransform: 'uppercase', border: true, divider: false },
    row: { height: 56, selectedAccent: true },
    cell: { padding: '14px 18px' },
    pagination: { variant: 'pill' },
    search: { variant: 'filled' },
    checkbox: { variant: 'rounded' },
  },

  minimal: {
    name: 'minimal',
    colors: {
      headerBackground: 'transparent',
      border: '#F1F5F9',
      rowHover: '#F1F5F9',
      rowSelected: '#E8EDF3',
      rowSelectedHover: '#DDE4EC',
    },
    borders: { outerBorder: false, headerBorder: true, rowBorder: true },
    shadows: { container: 'none' },
    radius: { container: '0px' },
    table: { variant: 'minimal' },
    header: { variant: 'transparent', height: 40 },
    row: { height: 48 },
    cell: { padding: '10px 12px' },
    pagination: { variant: 'minimal' },
    search: { variant: 'minimal' },
  },

  compact: {
    name: 'compact',
    density: 'compact',
    typography: { fontSize: '13px', headerFontSize: '12px' },
    header: { height: 40 },
    row: { height: 40 },
    cell: { padding: '6px 12px' },
    pagination: { variant: 'compact', size: 'sm' },
    search: { size: 'sm' },
  },

  comfortable: {
    name: 'comfortable',
    density: 'spacious',
    header: { height: 58 },
    row: { height: 64 },
    cell: { padding: '18px 20px', fontSize: '15px' },
  },

  enterprise: {
    name: 'enterprise',
    colors: {
      primary: '#0F62FE',
      headerBackground: '#F2F4F8',
      headerText: '#21272A',
      border: '#DDE1E6',
      rowHover: '#F2F4F8',
      rowSelected: '#EDF5FF',
    },
    borders: { columnBorder: true, outerBorder: true, rowBorder: true },
    radius: { container: '2px', md: '2px', sm: '2px' },
    shadows: { container: 'none' },
    density: 'compact',
    table: { variant: 'bordered' },
    header: { height: 40, textTransform: 'none', fontWeight: 600 },
    row: { height: 40 },
    cell: { padding: '8px 14px' },
    pagination: { variant: 'outlined', size: 'sm' },
    search: { variant: 'outlined', size: 'sm' },
    checkbox: { variant: 'square' },
  },

  material: {
    name: 'material',
    colors: {
      primary: '#6750A4',
      primaryHover: '#5B4A8F',
      headerBackground: '#FFFFFF',
      headerText: '#1D1B20',
      border: '#E7E0EC',
      rowHover: '#F7F2FA',
      rowSelected: '#EADDFF',
      rowSelectedHover: '#E0D0FA',
    },
    radius: { container: '16px', md: '8px', full: '9999px' },
    shadows: { container: '0 1px 3px rgba(0,0,0,.12), 0 1px 2px rgba(0,0,0,.08)' },
    typography: { fontFamily: 'Roboto, ui-sans-serif, system-ui, sans-serif' },
    header: { height: 52, fontWeight: 500 },
    row: { height: 52 },
    pagination: { variant: 'default' },
    search: { variant: 'filled', radius: '4px 4px 0 0' },
    checkbox: { variant: 'square' },
  },

  glass: {
    name: 'glass',
    colors: {
      background: 'rgba(255,255,255,0.55)',
      surface: 'rgba(255,255,255,0.6)',
      headerBackground: 'rgba(255,255,255,0.45)',
      rowBackground: 'transparent',
      rowHover: 'rgba(255,255,255,0.55)',
      rowSelected: 'rgba(99,102,241,0.14)',
      border: 'rgba(255,255,255,0.6)',
      borderStrong: 'rgba(255,255,255,0.8)',
    },
    radius: { container: '18px' },
    shadows: { container: '0 8px 32px rgba(31,38,135,.18)' },
    table: { className: 'sdg-glass' },
    header: { variant: 'transparent' },
    pagination: { variant: 'pill' },
    search: { variant: 'pill' },
  },

  soft: {
    name: 'soft',
    colors: {
      primary: '#6366F1',
      background: '#FBFBFE',
      surface: '#FFFFFF',
      headerBackground: '#F5F6FF',
      headerText: '#4B5563',
      border: '#EEF0F6',
      rowHover: '#EDEFFE',
      rowSelected: '#E0E3FD',
      rowSelectedHover: '#CFD4FB',
      hoverOverlay: 'rgba(99, 102, 241, 0.09)',
    },
    radius: { container: '16px', md: '10px', lg: '14px' },
    shadows: { container: '0 2px 16px rgba(99,102,241,.08)' },
    borders: { outerBorder: false, rowBorder: false },
    header: { height: 46, border: false },
    row: { height: 54, border: false, striped: true },
    pagination: { variant: 'pill' },
    search: { variant: 'rounded' },
    checkbox: { variant: 'circle' },
  },

  dark: {
    name: 'dark',
    mode: 'dark',
  },

  'high-contrast': {
    name: 'high-contrast',
    colors: {
      primary: '#0000EE',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#000000',
      textMuted: '#1A1A1A',
      border: '#000000',
      borderStrong: '#000000',
      headerBackground: '#000000',
      headerText: '#FFFFFF',
      rowHover: '#FFFF99',
      rowSelected: '#FFEE55',
      rowSelectedHover: '#FFE100',
      focusRing: '#FF0000',
    },
    borders: { width: '2px', columnBorder: true, outerBorder: true, rowBorder: true },
    radius: { container: '0px', md: '0px', sm: '0px', full: '0px' },
    shadows: { container: 'none' },
    typography: { fontWeight: 500, headerFontWeight: 700 },
    table: { variant: 'bordered' },
    checkbox: { variant: 'square' },
    dark: {
      colors: {
        background: '#000000',
        surface: '#000000',
        text: '#FFFFFF',
        border: '#FFFFFF',
        headerBackground: '#FFFFFF',
        headerText: '#000000',
        rowBackground: '#000000',
        rowHover: '#333300',
        rowSelected: '#555500',
      },
    },
  },

  rounded: {
    name: 'rounded',
    radius: { container: '20px', md: '12px', lg: '16px', sm: '8px' },
    header: { height: 50 },
    row: { height: 56 },
    pagination: { variant: 'pill' },
    search: { variant: 'pill' },
    checkbox: { variant: 'circle' },
    button: { radius: '9999px' },
  },

  sharp: {
    name: 'sharp',
    radius: { container: '0px', md: '0px', lg: '0px', sm: '0px', xl: '0px', full: '0px' },
    borders: { columnBorder: true },
    table: { variant: 'bordered' },
    pagination: { variant: 'outlined' },
    search: { variant: 'outlined' },
    checkbox: { variant: 'square' },
    button: { radius: '0px' },
  },

  borderless: {
    name: 'borderless',
    borders: { outerBorder: false, rowBorder: false, headerBorder: false, columnBorder: false },
    shadows: { container: 'none' },
    colors: { headerBackground: 'transparent' },
    table: { variant: 'borderless' },
    header: { border: false, variant: 'transparent' },
    row: { border: false, striped: true },
    pagination: { variant: 'simple' },
    search: { variant: 'minimal' },
  },

  dense: {
    name: 'dense',
    density: 'dense',
    typography: { fontSize: '12px', headerFontSize: '11px' },
    header: { height: 32 },
    row: { height: 30 },
    cell: { padding: '3px 8px' },
    table: { variant: 'dense' },
    pagination: { variant: 'compact', size: 'xs' },
    search: { size: 'xs' },
    checkbox: { size: 'sm' },
  },

  luxury: {
    name: 'luxury',
    colors: {
      primary: '#B08D57',
      primaryHover: '#9A7A49',
      primaryContrast: '#1B1712',
      background: '#FCFBF8',
      surface: '#FFFFFF',
      headerBackground: '#1B1712',
      headerText: '#E9DCC3',
      text: '#2A2520',
      textMuted: '#8A8175',
      border: '#EDE7DA',
      rowHover: '#FAF6EE',
      rowSelected: '#F5EDDD',
      rowSelectedHover: '#EFE3CC',
    },
    typography: {
      fontFamily: 'Georgia, "Times New Roman", ui-serif, serif',
      headerFontSize: '12px',
      letterSpacing: '0.06em',
    },
    radius: { container: '4px', md: '3px' },
    shadows: { container: '0 2px 24px rgba(27,23,18,.10)' },
    header: { height: 52, textTransform: 'uppercase' },
    row: { height: 58 },
    pagination: { variant: 'outlined' },
    search: { variant: 'outlined' },
  },

  dashboard: {
    name: 'dashboard',
    colors: {
      primary: '#0EA5E9',
      headerBackground: '#F8FAFC',
      headerText: '#475569',
      rowHover: '#F0F9FF',
      rowSelected: '#E0F2FE',
    },
    radius: { container: '12px' },
    density: 'compact',
    header: { height: 42, textTransform: 'uppercase', fontWeight: 600 },
    row: { height: 46, striped: false },
    cell: { padding: '8px 14px' },
    pagination: { variant: 'minimal', size: 'sm' },
    search: { variant: 'filled', size: 'sm' },
  },

  crm: {
    name: 'crm',
    colors: {
      primary: '#7C3AED',
      primaryHover: '#6D28D9',
      headerBackground: '#FAF5FF',
      headerText: '#5B21B6',
      rowHover: '#FAF5FF',
      rowSelected: '#F3E8FF',
      rowSelectedHover: '#E9D5FF',
    },
    radius: { container: '12px' },
    header: { height: 46 },
    row: { height: 56, selectedAccent: true },
    pagination: { variant: 'pill' },
    search: { variant: 'rounded' },
    actions: { display: 'dropdown', showOnHover: true },
  },

  hrms: {
    name: 'hrms',
    colors: {
      primary: '#0D9488',
      primaryHover: '#0F766E',
      headerBackground: '#F0FDFA',
      headerText: '#115E59',
      rowHover: '#F0FDFA',
      rowSelected: '#CCFBF1',
    },
    radius: { container: '12px' },
    header: { height: 48 },
    row: { height: 60 },
    cell: { padding: '12px 18px' },
    pagination: { variant: 'default' },
    search: { variant: 'filled' },
  },

  erp: {
    name: 'erp',
    colors: {
      primary: '#1D4ED8',
      headerBackground: '#EFF3F8',
      headerText: '#1E293B',
      border: '#D7DEE8',
      rowHover: '#F3F6FA',
    },
    borders: { columnBorder: true, rowBorder: true, outerBorder: true },
    radius: { container: '4px', md: '3px' },
    shadows: { container: 'none' },
    density: 'compact',
    table: { variant: 'bordered' },
    header: { height: 38, fontWeight: 600 },
    row: { height: 36 },
    cell: { padding: '6px 10px', fontSize: '13px' },
    pagination: { variant: 'outlined', size: 'sm' },
    search: { variant: 'outlined', size: 'sm' },
    checkbox: { variant: 'square', size: 'sm' },
  },

  saas: {
    name: 'saas',
    colors: {
      primary: '#111827',
      primaryHover: '#000000',
      headerBackground: '#FFFFFF',
      headerText: '#6B7280',
      border: '#F3F4F6',
      rowHover: '#F3F4F6',
      rowSelected: '#E5E7EB',
      rowSelectedHover: '#D9DCE1',
    },
    radius: { container: '12px', md: '8px' },
    shadows: { container: '0 1px 2px rgba(0,0,0,.04), 0 1px 3px rgba(0,0,0,.06)' },
    typography: { headerFontSize: '12px', headerFontWeight: 500 },
    header: { height: 44, divider: false },
    row: { height: 52 },
    pagination: { variant: 'simple' },
    search: { variant: 'outlined' },
  },

  analytics: {
    name: 'analytics',
    colors: {
      primary: '#059669',
      headerBackground: '#0F172A',
      headerText: '#E2E8F0',
      rowHover: '#F0FDF4',
      rowSelected: '#DCFCE7',
      border: '#E5E7EB',
    },
    radius: { container: '10px' },
    density: 'compact',
    typography: { monoFamily: 'ui-monospace, "SF Mono", Menlo, monospace' },
    header: { height: 44, textTransform: 'uppercase', fontSize: 12 },
    row: { height: 44, striped: true },
    cell: { padding: '8px 14px' },
    pagination: { variant: 'numbered', size: 'sm' },
    search: { variant: 'filled', size: 'sm' },
  },
};

export const themePresetNames = Object.keys(themePresets) as Array<Exclude<ThemePreset, 'system'>>;

export function isThemePreset(value: unknown): value is ThemePreset {
  return typeof value === 'string' && (value === 'system' || value in themePresets);
}
