import type { GridLabels } from '../types';

export const defaultLabels: GridLabels = {
  search: 'Search',
  searchPlaceholder: 'Search…',
  filter: 'Filter',
  filters: 'Filters',
  columns: 'Columns',
  export: 'Export',
  refresh: 'Refresh',
  density: 'Density',
  fullscreen: 'Fullscreen',
  exitFullscreen: 'Exit fullscreen',
  settings: 'Settings',
  addRow: 'Add row',
  selected: 'selected',
  clearSelection: 'Clear',
  noResults: 'No results',
  noResultsDescription: 'Try adjusting your search or filters.',
  loading: 'Loading…',
  error: 'Something went wrong',
  retry: 'Try again',
  save: 'Save',
  cancel: 'Cancel',
  undo: 'Undo',
  redo: 'Redo',
  apply: 'Apply',
  reset: 'Reset',
  addCondition: 'Add condition',
  addGroup: 'Add group',
  where: 'Where',
  showAll: 'Show all',
  hideAll: 'Hide all',
  pinLeft: 'Pin left',
  pinRight: 'Pin right',
  unpin: 'Unpin',
  sortAsc: 'Sort ascending',
  sortDesc: 'Sort descending',
  clearSort: 'Clear sort',
  groupBy: 'Group by',
  pagination: {
    first: 'First page',
    last: 'Last page',
    previous: 'Previous page',
    next: 'Next page',
    page: 'Page',
    of: 'of',
    rowsPerPage: 'Rows per page',
    jumpTo: 'Go to page',
    showing: 'Showing',
    results: 'results',
  },
};
